// Smart Dropdown Daten für Fahrzeuge
// Hersteller und Modelle für Premium SUVs und Limousinen

export const manufacturers = [
  { value: "audi", label: "Audi" },
  { value: "bmw", label: "BMW" },
  { value: "mercedes", label: "Mercedes-Benz" },
  { value: "porsche", label: "Porsche" },
  { value: "land-rover", label: "Land Rover" },
  { value: "range-rover", label: "Range Rover" },
  { value: "jaguar", label: "Jaguar" },
  { value: "bentley", label: "Bentley" },
  { value: "maserati", label: "Maserati" },
  { value: "ferrari", label: "Ferrari" },
  { value: "lamborghini", label: "Lamborghini" },
  { value: "volkswagen", label: "Volkswagen" },
  { value: "volvo", label: "Volvo" },
  { value: "lexus", label: "Lexus" },
  { value: "tesla", label: "Tesla" },
  { value: "alfa-romeo", label: "Alfa Romeo" },
] as const

export const models: Record<string, Array<{ value: string; label: string }>> = {
  audi: [
    { value: "a3", label: "A3" },
    { value: "a4", label: "A4" },
    { value: "a5", label: "A5" },
    { value: "a6", label: "A6" },
    { value: "a7", label: "A7" },
    { value: "a8", label: "A8" },
    { value: "q3", label: "Q3" },
    { value: "q5", label: "Q5" },
    { value: "q7", label: "Q7" },
    { value: "q8", label: "Q8" },
    { value: "e-tron", label: "e-tron" },
    { value: "e-tron-gt", label: "e-tron GT" },
    { value: "rs3", label: "RS3" },
    { value: "rs4", label: "RS4" },
    { value: "rs5", label: "RS5" },
    { value: "rs6", label: "RS6" },
    { value: "rs7", label: "RS7" },
    { value: "rsq8", label: "RS Q8" },
    { value: "s3", label: "S3" },
    { value: "s4", label: "S4" },
    { value: "s5", label: "S5" },
    { value: "s6", label: "S6" },
    { value: "s7", label: "S7" },
    { value: "s8", label: "S8" },
    { value: "sq5", label: "SQ5" },
    { value: "sq7", label: "SQ7" },
    { value: "sq8", label: "SQ8" },
    { value: "tt", label: "TT" },
    { value: "r8", label: "R8" },
  ],
  bmw: [
    { value: "1er", label: "1er" },
    { value: "2er", label: "2er" },
    { value: "3er", label: "3er" },
    { value: "4er", label: "4er" },
    { value: "5er", label: "5er" },
    { value: "6er", label: "6er" },
    { value: "7er", label: "7er" },
    { value: "8er", label: "8er" },
    { value: "x1", label: "X1" },
    { value: "x2", label: "X2" },
    { value: "x3", label: "X3" },
    { value: "x4", label: "X4" },
    { value: "x5", label: "X5" },
    { value: "x6", label: "X6" },
    { value: "x7", label: "X7" },
    { value: "xm", label: "XM" },
    { value: "z4", label: "Z4" },
    { value: "i3", label: "i3" },
    { value: "i4", label: "i4" },
    { value: "i5", label: "i5" },
    { value: "i7", label: "i7" },
    { value: "ix", label: "iX" },
    { value: "ix1", label: "iX1" },
    { value: "ix3", label: "iX3" },
    { value: "m2", label: "M2" },
    { value: "m3", label: "M3" },
    { value: "m4", label: "M4" },
    { value: "m5", label: "M5" },
    { value: "m8", label: "M8" },
  ],
  mercedes: [
    { value: "a-klasse", label: "A-Klasse" },
    { value: "b-klasse", label: "B-Klasse" },
    { value: "c-klasse", label: "C-Klasse" },
    { value: "e-klasse", label: "E-Klasse" },
    { value: "s-klasse", label: "S-Klasse" },
    { value: "cla", label: "CLA" },
    { value: "cls", label: "CLS" },
    { value: "gla", label: "GLA" },
    { value: "glb", label: "GLB" },
    { value: "glc", label: "GLC" },
    { value: "glc-coupe", label: "GLC Coupé" },
    { value: "gle", label: "GLE" },
    { value: "gle-coupe", label: "GLE Coupé" },
    { value: "gls", label: "GLS" },
    { value: "g-klasse", label: "G-Klasse" },
    { value: "eqa", label: "EQA" },
    { value: "eqb", label: "EQB" },
    { value: "eqc", label: "EQC" },
    { value: "eqe", label: "EQE" },
    { value: "eqs", label: "EQS" },
    { value: "eqs-suv", label: "EQS SUV" },
    { value: "amg-gt", label: "AMG GT" },
    { value: "sl", label: "SL" },
    { value: "maybach-s", label: "Maybach S-Klasse" },
    { value: "maybach-gls", label: "Maybach GLS" },
  ],
  porsche: [
    { value: "911", label: "911" },
    { value: "718-boxster", label: "718 Boxster" },
    { value: "718-cayman", label: "718 Cayman" },
    { value: "taycan", label: "Taycan" },
    { value: "panamera", label: "Panamera" },
    { value: "macan", label: "Macan" },
    { value: "cayenne", label: "Cayenne" },
    { value: "cayenne-coupe", label: "Cayenne Coupé" },
  ],
  "land-rover": [
    { value: "defender", label: "Defender" },
    { value: "discovery", label: "Discovery" },
    { value: "discovery-sport", label: "Discovery Sport" },
  ],
  "range-rover": [
    { value: "range-rover", label: "Range Rover" },
    { value: "range-rover-sport", label: "Range Rover Sport" },
    { value: "range-rover-velar", label: "Range Rover Velar" },
    { value: "evoque", label: "Range Rover Evoque" },
  ],
  jaguar: [
    { value: "f-pace", label: "F-PACE" },
    { value: "e-pace", label: "E-PACE" },
    { value: "i-pace", label: "I-PACE" },
    { value: "xe", label: "XE" },
    { value: "xf", label: "XF" },
    { value: "f-type", label: "F-TYPE" },
  ],
  bentley: [
    { value: "continental-gt", label: "Continental GT" },
    { value: "continental-gtc", label: "Continental GTC" },
    { value: "flying-spur", label: "Flying Spur" },
    { value: "bentayga", label: "Bentayga" },
  ],
  maserati: [
    { value: "ghibli", label: "Ghibli" },
    { value: "quattroporte", label: "Quattroporte" },
    { value: "levante", label: "Levante" },
    { value: "grecale", label: "Grecale" },
    { value: "mc20", label: "MC20" },
    { value: "granturismo", label: "GranTurismo" },
  ],
  ferrari: [
    { value: "roma", label: "Roma" },
    { value: "portofino", label: "Portofino M" },
    { value: "296-gtb", label: "296 GTB" },
    { value: "296-gts", label: "296 GTS" },
    { value: "sf90", label: "SF90 Stradale" },
    { value: "f8-tributo", label: "F8 Tributo" },
    { value: "812", label: "812 Superfast" },
    { value: "purosangue", label: "Purosangue" },
  ],
  lamborghini: [
    { value: "huracan", label: "Huracán" },
    { value: "urus", label: "Urus" },
    { value: "revuelto", label: "Revuelto" },
  ],
  volkswagen: [
    { value: "golf", label: "Golf" },
    { value: "passat", label: "Passat" },
    { value: "arteon", label: "Arteon" },
    { value: "tiguan", label: "Tiguan" },
    { value: "touareg", label: "Touareg" },
    { value: "t-roc", label: "T-Roc" },
    { value: "id4", label: "ID.4" },
    { value: "id5", label: "ID.5" },
    { value: "id7", label: "ID.7" },
  ],
  volvo: [
    { value: "xc40", label: "XC40" },
    { value: "xc60", label: "XC60" },
    { value: "xc90", label: "XC90" },
    { value: "s60", label: "S60" },
    { value: "s90", label: "S90" },
    { value: "v60", label: "V60" },
    { value: "v90", label: "V90" },
    { value: "c40", label: "C40 Recharge" },
    { value: "ex30", label: "EX30" },
    { value: "ex90", label: "EX90" },
  ],
  lexus: [
    { value: "es", label: "ES" },
    { value: "is", label: "IS" },
    { value: "ls", label: "LS" },
    { value: "nx", label: "NX" },
    { value: "rx", label: "RX" },
    { value: "lx", label: "LX" },
    { value: "ux", label: "UX" },
    { value: "lc", label: "LC" },
    { value: "rz", label: "RZ" },
  ],
  tesla: [
    { value: "model-3", label: "Model 3" },
    { value: "model-s", label: "Model S" },
    { value: "model-x", label: "Model X" },
    { value: "model-y", label: "Model Y" },
  ],
  "alfa-romeo": [
    { value: "giulia", label: "Giulia" },
    { value: "stelvio", label: "Stelvio" },
    { value: "tonale", label: "Tonale" },
  ],
}

export const fuelTypes = [
  { value: "BENZIN", label: "Benzin" },
  { value: "DIESEL", label: "Diesel" },
  { value: "ELEKTRO", label: "Elektro" },
  { value: "HYBRID", label: "Hybrid" },
  { value: "LPG", label: "LPG/Autogas" },
] as const

export const transmissions = [
  { value: "AUTOMATIK", label: "Automatik" },
  { value: "MANUELL", label: "Manuell" },
] as const

export const driveTypes = [
  { value: "FRONT", label: "Frontantrieb" },
  { value: "HECK", label: "Heckantrieb" },
  { value: "ALLRAD", label: "Allradantrieb" },
] as const

export const vehicleTypes = [
  { value: "PKW", label: "PKW" },
  { value: "SUV", label: "SUV" },
  { value: "KOMBI", label: "Kombi" },
  { value: "COUPE", label: "Coupé" },
  { value: "CABRIO", label: "Cabrio" },
  { value: "LIMOUSINE", label: "Limousine" },
  { value: "VAN", label: "Van" },
] as const

export const vehicleConditions = [
  { value: "NEU", label: "Neuwagen" },
  { value: "GEBRAUCHT", label: "Gebrauchtwagen" },
  { value: "JAHRESWAGEN", label: "Jahreswagen" },
  { value: "VORFUEHRWAGEN", label: "Vorführwagen" },
] as const

export const vehicleStatuses = [
  { value: "ENTWURF", label: "Entwurf" },
  { value: "AKTIV", label: "Aktiv" },
  { value: "RESERVIERT", label: "Reserviert" },
  { value: "VERKAUFT", label: "Verkauft" },
] as const

export const exteriorColors = [
  { value: "schwarz", label: "Schwarz" },
  { value: "weiss", label: "Weiß" },
  { value: "silber", label: "Silber" },
  { value: "grau", label: "Grau" },
  { value: "blau", label: "Blau" },
  { value: "rot", label: "Rot" },
  { value: "gruen", label: "Grün" },
  { value: "braun", label: "Braun" },
  { value: "beige", label: "Beige" },
  { value: "gold", label: "Gold" },
  { value: "orange", label: "Orange" },
  { value: "gelb", label: "Gelb" },
] as const

export const features = [
  // Komfort
  "Klimaautomatik",
  "2-Zonen Klimaautomatik",
  "4-Zonen Klimaautomatik",
  "Sitzheizung vorne",
  "Sitzheizung hinten",
  "Sitzbelüftung",
  "Massagesitze",
  "Elektrische Sitze",
  "Memory-Sitze",
  "Lenkradheizung",
  "Panoramadach",
  "Panorama-Glasdach",
  "Schiebedach",
  "Elektrische Heckklappe",
  "Keyless Entry",
  "Keyless Go",
  "Ambiente-Beleuchtung",
  
  // Multimedia
  "Navigationssystem",
  "Head-up Display",
  "Soundsystem Premium",
  "Harman Kardon",
  "Bose Sound",
  "Bang & Olufsen",
  "Burmester",
  "Apple CarPlay",
  "Android Auto",
  "Wireless Charging",
  "DAB Radio",
  "Rückfahrkamera",
  "360° Kamera",
  "TV-Funktion",
  
  // Sicherheit
  "Einparkhilfe vorne",
  "Einparkhilfe hinten",
  "Parklenkassistent",
  "Spurhalteassistent",
  "Spurwechselassistent",
  "Totwinkelwarner",
  "Abstandstempomat",
  "Notbremsassistent",
  "Verkehrszeichenerkennung",
  "Nachtsichtassistent",
  "Müdigkeitserkennung",
  "Cross Traffic Alert",
  
  // Licht
  "LED-Scheinwerfer",
  "Matrix-LED",
  "Laserlicht",
  "Kurvenlicht",
  "Fernlichtassistent",
  "LED-Rückleuchten",
  
  // Exterieur
  "Sportpaket",
  "AMG-Line",
  "M-Sportpaket",
  "S-Line",
  "Luftfederung",
  "Anhängerkupplung",
  "Dachgepäckträger",
  
  // Interieur
  "Ledersitze",
  "Alcantara",
  "Sportlenkrad",
  "Digitalcockpit",
  "Multifunktionslenkrad",
  
  // Fahrassistenz
  "Tempomat",
  "Geschwindigkeitsbegrenzer",
  "Start-Stop-Automatik",
  "Berganfahrassistent",
] as const

